version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "employee-sam-2"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-169rtx0muna8d"
s3_prefix = "employee-sam-2"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
